# Generated by Django 4.0.2 on 2023-02-23 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_typecar_alter_category_table_product_typecar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typecar',
            options={},
        ),
    ]
