# Generated by Django 4.0.2 on 2023-02-23 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_typecar_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typecar',
            options={'ordering': ('nametype',)},
        ),
    ]
