# Generated by Django 4.0.2 on 2023-02-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_typecar_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(max_length=4)),
                ('name', models.CharField(max_length=200)),
                ('sedanPrice', models.IntegerField()),
                ('UniversalPrice', models.IntegerField()),
                ('PicapPrice', models.IntegerField()),
            ],
        ),
    ]
