# Generated by Django 4.0.2 on 2023-02-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='code',
            field=models.IntegerField(),
        ),
    ]
