# Generated by Django 4.0.2 on 2023-02-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_services_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='PicapPrice',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='UniversalPrice',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='sedanPrice',
            field=models.IntegerField(null=True),
        ),
    ]
