# Generated by Django 4.1.4 on 2023-02-25 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_services_picapprice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spare_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='Spare/')),
            ],
            options={
                'db_table': 'Spare',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Spare_part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sCategory', to='product.spare_category')),
            ],
        ),
    ]
