# Generated by Django 4.1.4 on 2023-02-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_spare_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='spare_part',
            name='image',
            field=models.ImageField(default=1, upload_to='productSpare/'),
            preserve_default=False,
        ),
    ]
